CREATE TABLE acceptances (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP,
    pickup_point_id REFERENCES pickup_points(id) ON DELETE CASCADE,
    status_id REFERENCES statuses(status_id)
);
