CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    acceptance_date TIMESTAMP,
    category_id REFERENCES categories(category_id) ON DELETE CASCADE
);
