FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o migrator ./cmd/migrator/main.go

FROM alpine:3.23
RUN apk --no-cache add postgresql-client
WORKDIR /app
COPY --from=builder /app/config ./config/
COPY --from=builder /app/migrator /app/migrator
COPY --from=builder /app/migrations /app/migrations
ENTRYPOINT ["./migrator"]